# Generated by Django 5.0.1 on 2024-03-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
