# Generated by Django 5.0.1 on 2024-03-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
